#!/usr/bin/python -u
print "Compute Optimized - Current Generation"
brenda-run -i c4.large price
brenda-run -i c4.xlarge price
brenda-run -i c4.2xlarge price
brenda-run -i c4.4xlarge price
brenda-run -i c4.8xlarge price
print ""
brenda-run -i c3.large price
brenda-run -i c3.xlarge price
brenda-run -i c3.2xlarge price
brenda-run -i c3.4xlarge price
brenda-run -i c3.8xlarge price
print ""
print "--"
print ""
print "GPU Instances - Current Generation"
brenda-run -i g2.2xlarge price
brenda-run -i g2.8xlarge price

sys.exit(2)